<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RubroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rubros')->insert(array('id' => '1','nombre' => 'Alimentos'));
        DB::table('rubros')->insert(array('id' => '2','nombre' => 'Art. de Limpieza'));
        DB::table('rubros')->insert(array('id' => '3','nombre' => 'Art. del Hogar'));
        DB::table('rubros')->insert(array('id' => '4','nombre' => 'Art. Infantiles'));
        DB::table('rubros')->insert(array('id' => '5','nombre' => 'Artesanias'));
        DB::table('rubros')->insert(array('id' => '6','nombre' => 'Audiología'));
        DB::table('rubros')->insert(array('id' => '7','nombre' => 'Bazar'));
        DB::table('rubros')->insert(array('id' => '8','nombre' => 'Belleza'));
        DB::table('rubros')->insert(array('id' => '9','nombre' => 'Bicicleteria'));
        DB::table('rubros')->insert(array('id' => '10','nombre' => 'Blanqueria'));
        DB::table('rubros')->insert(array('id' => '11','nombre' => 'Calzados'));
        DB::table('rubros')->insert(array('id' => '12','nombre' => 'Carniceria'));
        DB::table('rubros')->insert(array('id' => '13','nombre' => 'Carpinteria'));
        DB::table('rubros')->insert(array('id' => '14','nombre' => 'Cine'));
        DB::table('rubros')->insert(array('id' => '15','nombre' => 'Colchoneria'));
        DB::table('rubros')->insert(array('id' => '16','nombre' => 'Construccion'));
        DB::table('rubros')->insert(array('id' => '17','nombre' => 'Cotillon'));
        DB::table('rubros')->insert(array('id' => '18','nombre' => 'Decoración'));
        DB::table('rubros')->insert(array('id' => '19','nombre' => 'Deportes'));
        DB::table('rubros')->insert(array('id' => '20','nombre' => 'Disqueria'));
        DB::table('rubros')->insert(array('id' => '21','nombre' => 'Electronica'));
        DB::table('rubros')->insert(array('id' => '22','nombre' => 'Electricidad e Iluminacion'));
        DB::table('rubros')->insert(array('id' => '23','nombre' => 'Electrodomesticos'));
        DB::table('rubros')->insert(array('id' => '24','nombre' => 'Entretenimiento'));
        DB::table('rubros')->insert(array('id' => '25','nombre' => 'Estacion de Servicio'));
        DB::table('rubros')->insert(array('id' => '26','nombre' => 'Farmacia'));
        DB::table('rubros')->insert(array('id' => '27','nombre' => 'Ferreteria'));
        DB::table('rubros')->insert(array('id' => '28','nombre' => 'Floreria'));
        DB::table('rubros')->insert(array('id' => '29','nombre' => 'Fotografia'));
        DB::table('rubros')->insert(array('id' => '30','nombre' => 'Gastronomia'));
        DB::table('rubros')->insert(array('id' => '31','nombre' => 'Gimnasio'));
        DB::table('rubros')->insert(array('id' => '32','nombre' => 'Heladeria'));
        DB::table('rubros')->insert(array('id' => '33','nombre' => 'Hoteleria'));
        DB::table('rubros')->insert(array('id' => '34','nombre' => 'Indumentaria'));
        DB::table('rubros')->insert(array('id' => '35','nombre' => 'Informatica'));
        DB::table('rubros')->insert(array('id' => '36','nombre' => 'Instrumentos musicales'));
        DB::table('rubros')->insert(array('id' => '37','nombre' => 'Joyeria'));
        DB::table('rubros')->insert(array('id' => '38','nombre' => 'Jugueteria'));
        DB::table('rubros')->insert(array('id' => '39','nombre' => 'Lenceria'));
        DB::table('rubros')->insert(array('id' => '40','nombre' => 'Libreria'));
        DB::table('rubros')->insert(array('id' => '41','nombre' => 'Mascotas'));
        DB::table('rubros')->insert(array('id' => '42','nombre' => 'Merceria'));
        DB::table('rubros')->insert(array('id' => '43','nombre' => 'Metalurgica'));
        DB::table('rubros')->insert(array('id' => '44','nombre' => 'Muebleria'));
        DB::table('rubros')->insert(array('id' => '45','nombre' => 'Optica'));
        DB::table('rubros')->insert(array('id' => '46','nombre' => 'Ortopedia'));
        DB::table('rubros')->insert(array('id' => '47','nombre' => 'Papeleria'));
        DB::table('rubros')->insert(array('id' => '48','nombre' => 'Peluqueria'));
        DB::table('rubros')->insert(array('id' => '49','nombre' => 'Perfumeria'));
        DB::table('rubros')->insert(array('id' => '50','nombre' => 'Pesca y Camping'));
        DB::table('rubros')->insert(array('id' => '51','nombre' => 'Pintureria'));
        DB::table('rubros')->insert(array('id' => '52','nombre' => 'Piscinas'));
        DB::table('rubros')->insert(array('id' => '53','nombre' => 'Regalos y Accesorios'));
        DB::table('rubros')->insert(array('id' => '54','nombre' => 'Relojeria'));
        DB::table('rubros')->insert(array('id' => '55','nombre' => 'Repuestos Automotor'));
        DB::table('rubros')->insert(array('id' => '56','nombre' => 'Rodados'));
        DB::table('rubros')->insert(array('id' => '57','nombre' => 'Sanitarios'));
        DB::table('rubros')->insert(array('id' => '58','nombre' => 'Seguridad'));
        DB::table('rubros')->insert(array('id' => '59','nombre' => 'Servicio Domiciliario'));
        DB::table('rubros')->insert(array('id' => '60','nombre' => 'Suministros Medicos'));
        DB::table('rubros')->insert(array('id' => '61','nombre' => 'Supermercado'));
        DB::table('rubros')->insert(array('id' => '62','nombre' => 'Talabarteria y Marroquineria'));
        DB::table('rubros')->insert(array('id' => '63','nombre' => 'Tapiceria'));
        DB::table('rubros')->insert(array('id' => '64','nombre' => 'Teatro'));
        DB::table('rubros')->insert(array('id' => '65','nombre' => 'Telefonia'));
        DB::table('rubros')->insert(array('id' => '66','nombre' => 'Textil'));
        DB::table('rubros')->insert(array('id' => '67','nombre' => 'Tienda'));
        DB::table('rubros')->insert(array('id' => '68','nombre' => 'Transporte'));
        DB::table('rubros')->insert(array('id' => '69','nombre' => 'Turismo'));
        DB::table('rubros')->insert(array('id' => '70','nombre' => 'Venta de Maquinaria'));
        DB::table('rubros')->insert(array('id' => '71','nombre' => 'Venta e instalacion de GNC'));
        DB::table('rubros')->insert(array('id' => '72','nombre' => 'Vidrieria'));
        DB::table('rubros')->insert(array('id' => '73','nombre' => 'Vinoteca'));
        DB::table('rubros')->insert(array('id' => '75','nombre' => 'Panaderia'));
        DB::table('rubros')->insert(array('id' => '76','nombre' => 'Confiteria'));
        DB::table('rubros')->insert(array('id' => '77','nombre' => 'Remiseria'));
        DB::table('rubros')->insert(array('id' => '78','nombre' => 'Aberturas '));
        DB::table('rubros')->insert(array('id' => '79','nombre' => 'Autoradio'));
        DB::table('rubros')->insert(array('id' => '80','nombre' => 'Corralon'));
        DB::table('rubros')->insert(array('id' => '81','nombre' => 'Corralon de materiales'));
        DB::table('rubros')->insert(array('id' => '82','nombre' => 'Inmobiliaria'));
        DB::table('rubros')->insert(array('id' => '83','nombre' => 'Casa de deportes'));
        DB::table('rubros')->insert(array('id' => '85','nombre' => 'Consultorios odontologicos'));
        DB::table('rubros')->insert(array('id' => '86','nombre' => 'Taller mecanico'));
        DB::table('rubros')->insert(array('id' => '87','nombre' => 'Amoblamientos'));
        DB::table('rubros')->insert(array('id' => '88','nombre' => 'Agencia de motos'));
        DB::table('rubros')->insert(array('id' => '89','nombre' => 'Agencia de autos'));
        DB::table('rubros')->insert(array('id' => '90','nombre' => 'Taller de chapa y pintura'));
        DB::table('rubros')->insert(array('id' => '91','nombre' => 'Salon de fiestas'));
        DB::table('rubros')->insert(array('id' => '92','nombre' => 'Estudio de arquitectura'));
        DB::table('rubros')->insert(array('id' => '93','nombre' => 'Parrilla restaurante'));
        DB::table('rubros')->insert(array('id' => '94','nombre' => 'Matafuegos'));
        DB::table('rubros')->insert(array('id' => '95','nombre' => 'Productor de seguros'));
        DB::table('rubros')->insert(array('id' => '96','nombre' => 'Pizzeria'));
        DB::table('rubros')->insert(array('id' => '97','nombre' => 'Casa de comidas'));
        DB::table('rubros')->insert(array('id' => '98','nombre' => 'Lavadero de autos'));
        DB::table('rubros')->insert(array('id' => '99','nombre' => 'Matriculados'));
        DB::table('rubros')->insert(array('id' => '100','nombre' => 'Matriculados gas'));
        DB::table('rubros')->insert(array('id' => '101','nombre' => 'Zapateria'));
        DB::table('rubros')->insert(array('id' => '102','nombre' => 'Empresa de construccion'));
        DB::table('rubros')->insert(array('id' => '104','nombre' => 'Zingueria'));
        DB::table('rubros')->insert(array('id' => '105','nombre' => 'Piscinas'));
        DB::table('rubros')->insert(array('id' => '106','nombre' => 'Limpieza de piscinas'));
        DB::table('rubros')->insert(array('id' => '107','nombre' => 'Construccion de piscinas'));
        DB::table('rubros')->insert(array('id' => '108','nombre' => 'Piletas'));
        DB::table('rubros')->insert(array('id' => '109','nombre' => 'Fotocopiadoras'));
        DB::table('rubros')->insert(array('id' => '110','nombre' => 'Durlock'));
        DB::table('rubros')->insert(array('id' => '111','nombre' => 'Placas y aglomerados'));
        DB::table('rubros')->insert(array('id' => '112','nombre' => 'Bicicletas Ventas'));
        DB::table('rubros')->insert(array('id' => '113','nombre' => 'Bicicletas reparacion'));
        DB::table('rubros')->insert(array('id' => '114','nombre' => 'Ropa de mujer'));
        DB::table('rubros')->insert(array('id' => '115','nombre' => 'Ropa de hombres'));
        DB::table('rubros')->insert(array('id' => '116','nombre' => 'Casa de ropa'));
        DB::table('rubros')->insert(array('id' => '117','nombre' => 'Ropa informal'));
        DB::table('rubros')->insert(array('id' => '118','nombre' => 'Uniformes colegiales'));
        DB::table('rubros')->insert(array('id' => '119','nombre' => 'Tiendas de ropa'));
        DB::table('rubros')->insert(array('id' => '120','nombre' => 'Celulares'));
        DB::table('rubros')->insert(array('id' => '121','nombre' => 'Reparacion de celulares'));
        DB::table('rubros')->insert(array('id' => '122','nombre' => 'Casa de celulares'));
        DB::table('rubros')->insert(array('id' => '123','nombre' => 'Sanitarios'));
        DB::table('rubros')->insert(array('id' => '126','nombre' => 'Perros'));
        DB::table('rubros')->insert(array('id' => '127','nombre' => 'Tiendas de mascotas'));
        DB::table('rubros')->insert(array('id' => '128','nombre' => 'Hierros'));
        DB::table('rubros')->insert(array('id' => '129','nombre' => 'Metales'));
        DB::table('rubros')->insert(array('id' => '130','nombre' => 'Carteras'));
        DB::table('rubros')->insert(array('id' => '131','nombre' => 'Accesorios'));
        DB::table('rubros')->insert(array('id' => '132','nombre' => 'Bijouterie'));
        DB::table('rubros')->insert(array('id' => '133','nombre' => 'Kiosco - Polirrubro'));
        DB::table('rubros')->insert(array('id' => '134','nombre' => 'Compostura de ropa'));
        DB::table('rubros')->insert(array('id' => '135','nombre' => 'Arreglos de ropa'));
        DB::table('rubros')->insert(array('id' => '136','nombre' => 'Granja'));
        DB::table('rubros')->insert(array('id' => '137','nombre' => 'Almacen'));
        DB::table('rubros')->insert(array('id' => '138','nombre' => 'Fiambreria'));
        DB::table('rubros')->insert(array('id' => '139','nombre' => 'Colegios'));
        DB::table('rubros')->insert(array('id' => '140','nombre' => 'Jardin infantes'));
        DB::table('rubros')->insert(array('id' => '141','nombre' => 'Bares'));
        DB::table('rubros')->insert(array('id' => '142','nombre' => 'Pubs'));
        DB::table('rubros')->insert(array('id' => '143','nombre' => 'Boliches'));
        DB::table('rubros')->insert(array('id' => '144','nombre' => 'Colchones'));
        DB::table('rubros')->insert(array('id' => '145','nombre' => 'Sillones'));
        DB::table('rubros')->insert(array('id' => '148','nombre' => 'Dietetica'));
        DB::table('rubros')->insert(array('id' => '149','nombre' => 'Empanadas'));
        DB::table('rubros')->insert(array('id' => '150','nombre' => 'Opticas'));
        DB::table('rubros')->insert(array('id' => '151','nombre' => 'Lentes'));
        DB::table('rubros')->insert(array('id' => '152','nombre' => 'Lubricentro'));
        DB::table('rubros')->insert(array('id' => '153','nombre' => 'Casa de repuestos'));
        DB::table('rubros')->insert(array('id' => '154','nombre' => 'Salon de fiestas infatiles'));
        DB::table('rubros')->insert(array('id' => '155','nombre' => 'Futbol'));
        DB::table('rubros')->insert(array('id' => '156','nombre' => 'Canchas de futbol'));
        DB::table('rubros')->insert(array('id' => '157','nombre' => 'Gomeria'));
        DB::table('rubros')->insert(array('id' => '159','nombre' => 'Cafe'));
        DB::table('rubros')->insert(array('id' => '160','nombre' => 'Restaurant'));
        DB::table('rubros')->insert(array('id' => '161','nombre' => 'Minutas'));
        DB::table('rubros')->insert(array('id' => '162','nombre' => 'Reparacion de pc'));
        DB::table('rubros')->insert(array('id' => '163','nombre' => 'Ventas de celulares'));
        DB::table('rubros')->insert(array('id' => '164','nombre' => 'Ventas de pc'));
        DB::table('rubros')->insert(array('id' => '165','nombre' => 'Ventas de juegos'));
        DB::table('rubros')->insert(array('id' => '166','nombre' => 'Ventas de play'));
        DB::table('rubros')->insert(array('id' => '167','nombre' => 'Vidrierista'));
        DB::table('rubros')->insert(array('id' => '168','nombre' => 'Hotel'));
        DB::table('rubros')->insert(array('id' => '169','nombre' => 'Albergue transitorio'));
        DB::table('rubros')->insert(array('id' => '170','nombre' => 'Hotel alojamientos'));
        DB::table('rubros')->insert(array('id' => '171','nombre' => 'Imprenta'));
        DB::table('rubros')->insert(array('id' => '172','nombre' => 'Servicio tecnico gral'));
        DB::table('rubros')->insert(array('id' => '173','nombre' => 'Veterinaria'));
        DB::table('rubros')->insert(array('id' => '174','nombre' => 'GNC'));
        DB::table('rubros')->insert(array('id' => '175','nombre' => 'Inyeccion electronica'));
        DB::table('rubros')->insert(array('id' => '176','nombre' => 'Neumaticos'));
        DB::table('rubros')->insert(array('id' => '177','nombre' => 'Tren delantero'));
        DB::table('rubros')->insert(array('id' => '178','nombre' => 'Frenos'));
        DB::table('rubros')->insert(array('id' => '179','nombre' => 'Llantas'));
        DB::table('rubros')->insert(array('id' => '180','nombre' => 'Refrigeracion'));
        DB::table('rubros')->insert(array('id' => '181','nombre' => 'Instalaciones comerciales'));
        DB::table('rubros')->insert(array('id' => '182','nombre' => 'Balneario'));
        DB::table('rubros')->insert(array('id' => '184','nombre' => 'Obra de teatro'));
        DB::table('rubros')->insert(array('id' => '185','nombre' => 'Resto'));
        DB::table('rubros')->insert(array('id' => '186','nombre' => 'Eventos'));
        DB::table('rubros')->insert(array('id' => '188','nombre' => 'Agasajos'));
        DB::table('rubros')->insert(array('id' => '189','nombre' => 'Pizzas'));
        DB::table('rubros')->insert(array('id' => '190','nombre' => 'Picadas'));
        DB::table('rubros')->insert(array('id' => '191','nombre' => 'Cerveza'));
        DB::table('rubros')->insert(array('id' => '192','nombre' => 'Cerveza Artesanal'));
        DB::table('rubros')->insert(array('id' => '196','nombre' => 'Corseteria'));
        DB::table('rubros')->insert(array('id' => '197','nombre' => 'Medias'));
        DB::table('rubros')->insert(array('id' => '198','nombre' => 'Mallas'));
        DB::table('rubros')->insert(array('id' => '205','nombre' => 'Tecnologia web'));
        DB::table('rubros')->insert(array('id' => '206','nombre' => 'Todos'));
        DB::table('rubros')->insert(array('id' => '207','nombre' => 'Servicio de hosting'));
        DB::table('rubros')->insert(array('id' => '208','nombre' => 'Transporte y Logistica'));
        DB::table('rubros')->insert(array('id' => '209','nombre' => 'Logistica y Distribucion'));
        DB::table('rubros')->insert(array('id' => '210','nombre' => 'Pet Shop'));
        DB::table('rubros')->insert(array('id' => '211','nombre' => 'Autoservicios'));
        DB::table('rubros')->insert(array('id' => '212','nombre' => 'Rotiserias'));
        DB::table('rubros')->insert(array('id' => '213','nombre' => 'Despensa y Fiambreria'));
        DB::table('rubros')->insert(array('id' => '214','nombre' => 'Carnicerias'));
        DB::table('rubros')->insert(array('id' => '215','nombre' => 'Frigorifico'));
        DB::table('rubros')->insert(array('id' => '216','nombre' => 'Chacinados'));
        DB::table('rubros')->insert(array('id' => '217','nombre' => 'Comidas para Llevar'));
        DB::table('rubros')->insert(array('id' => '218','nombre' => 'Panificadora'));
        DB::table('rubros')->insert(array('id' => '219','nombre' => 'Confiteria y Servicio de Lunch'));
        DB::table('rubros')->insert(array('id' => '220','nombre' => 'Pastas Frescas'));
        DB::table('rubros')->insert(array('id' => '221','nombre' => 'Fabrica de Sandwiches'));
        DB::table('rubros')->insert(array('id' => '222','nombre' => 'Frutas desecadas'));
        DB::table('rubros')->insert(array('id' => '223','nombre' => 'Insumos informáticos'));
        DB::table('rubros')->insert(array('id' => '224','nombre' => 'Pescaderia'));
        DB::table('rubros')->insert(array('id' => '226','nombre' => 'Comidas Dieteticas'));
        DB::table('rubros')->insert(array('id' => '228','nombre' => 'Venta Cafe, Te y Especias'));
        DB::table('rubros')->insert(array('id' => '230','nombre' => 'Vinos'));
        DB::table('rubros')->insert(array('id' => '231','nombre' => 'Verduleria y Fruteria '));
        DB::table('rubros')->insert(array('id' => '232','nombre' => 'Bebidas'));
        DB::table('rubros')->insert(array('id' => '233','nombre' => 'Lacteos'));
        DB::table('rubros')->insert(array('id' => '235','nombre' => 'Queseria'));
        DB::table('rubros')->insert(array('id' => '236','nombre' => 'Galletiteria '));
        DB::table('rubros')->insert(array('id' => '237','nombre' => 'Cafe Molido '));
        DB::table('rubros')->insert(array('id' => '238','nombre' => 'Golosinas'));
        DB::table('rubros')->insert(array('id' => '239','nombre' => 'Productos de granja y Regionales'));
        DB::table('rubros')->insert(array('id' => '240','nombre' => 'Distribuidora de cafe, golosinas y helados'));
        DB::table('rubros')->insert(array('id' => '241','nombre' => 'Articulos de punto y sweters'));
        DB::table('rubros')->insert(array('id' => '242','nombre' => 'Articulos de vestir'));
        DB::table('rubros')->insert(array('id' => '243','nombre' => 'Bebes y ninos'));
        DB::table('rubros')->insert(array('id' => '244','nombre' => 'Boutique '));
        DB::table('rubros')->insert(array('id' => '245','nombre' => 'Vestimenta para Jovenes'));
        DB::table('rubros')->insert(array('id' => '246','nombre' => 'Damas'));
        DB::table('rubros')->insert(array('id' => '247','nombre' => 'Futura mama'));
        DB::table('rubros')->insert(array('id' => '248','nombre' => 'Ropa para hombres'));
        DB::table('rubros')->insert(array('id' => '249','nombre' => 'Botoneria'));
        DB::table('rubros')->insert(array('id' => '250','nombre' => 'Camiseria'));
        DB::table('rubros')->insert(array('id' => '251','nombre' => 'Camperas'));
        DB::table('rubros')->insert(array('id' => '252','nombre' => 'Confecciones ropa'));
        DB::table('rubros')->insert(array('id' => '253','nombre' => 'Cuero y Marroquineria'));
        DB::table('rubros')->insert(array('id' => '254','nombre' => 'Talabarteria '));
        DB::table('rubros')->insert(array('id' => '255','nombre' => 'Ropa para damas, caballeros y ninos'));
        DB::table('rubros')->insert(array('id' => '256','nombre' => 'Ropa de cuero'));
        DB::table('rubros')->insert(array('id' => '257','nombre' => 'Novias'));
        DB::table('rubros')->insert(array('id' => '258','nombre' => 'Lanas e hilos'));
        DB::table('rubros')->insert(array('id' => '259','nombre' => 'Ropa para damas'));
        DB::table('rubros')->insert(array('id' => '260','nombre' => 'Paraguas'));
        DB::table('rubros')->insert(array('id' => '261','nombre' => 'Medias'));
        DB::table('rubros')->insert(array('id' => '262','nombre' => 'Mallas'));
        DB::table('rubros')->insert(array('id' => '263','nombre' => 'Repuestos camiones '));
        DB::table('rubros')->insert(array('id' => '265','nombre' => 'Roperia '));
        DB::table('rubros')->insert(array('id' => '266','nombre' => 'Panuelos'));
        DB::table('rubros')->insert(array('id' => '267','nombre' => 'Pantalones '));
        DB::table('rubros')->insert(array('id' => '268','nombre' => 'Pilotos'));
        DB::table('rubros')->insert(array('id' => '269','nombre' => 'Peleteria'));
        DB::table('rubros')->insert(array('id' => '270','nombre' => 'Retaceria'));
        DB::table('rubros')->insert(array('id' => '271','nombre' => 'Jean'));
        DB::table('rubros')->insert(array('id' => '272','nombre' => 'Polleras'));
        DB::table('rubros')->insert(array('id' => '273','nombre' => 'Alquiler de ropa'));
        DB::table('rubros')->insert(array('id' => '274','nombre' => 'Sastreria'));
        DB::table('rubros')->insert(array('id' => '275','nombre' => 'Sederia'));
        DB::table('rubros')->insert(array('id' => '276','nombre' => 'Vestidos de novia'));
        DB::table('rubros')->insert(array('id' => '277','nombre' => 'Articulos de comunion'));
        DB::table('rubros')->insert(array('id' => '279','nombre' => 'Guardapolvos escolares'));
        DB::table('rubros')->insert(array('id' => '280','nombre' => 'Uniformes escolares'));
        DB::table('rubros')->insert(array('id' => '281','nombre' => 'Zapatilleria'));
        DB::table('rubros')->insert(array('id' => '282','nombre' => 'Casa de deportes'));
        DB::table('rubros')->insert(array('id' => '283','nombre' => 'Zapatilleria compostura'));
        DB::table('rubros')->insert(array('id' => '284','nombre' => 'Zapateria damas, caballeros y ninos'));
        DB::table('rubros')->insert(array('id' => '285','nombre' => 'zapateria hombres'));
        DB::table('rubros')->insert(array('id' => '286','nombre' => 'zapateria damas'));
        DB::table('rubros')->insert(array('id' => '287','nombre' => 'Zapateria ninos'));
        DB::table('rubros')->insert(array('id' => '288','nombre' => 'Estampados y tenidos '));
        DB::table('rubros')->insert(array('id' => '289','nombre' => 'Articulos de goma'));
        DB::table('rubros')->insert(array('id' => '290','nombre' => 'Autorradios'));
        DB::table('rubros')->insert(array('id' => '291','nombre' => 'Canos de escape'));
        DB::table('rubros')->insert(array('id' => '292','nombre' => 'Academia de conductores'));
        DB::table('rubros')->insert(array('id' => '293','nombre' => 'Carburacion y afinacion'));
        DB::table('rubros')->insert(array('id' => '294','nombre' => 'Cerrajeria'));
        DB::table('rubros')->insert(array('id' => '295','nombre' => 'Chapa y pintura'));
        DB::table('rubros')->insert(array('id' => '297','nombre' => 'Baterias Automotor'));
        DB::table('rubros')->insert(array('id' => '298','nombre' => 'Equipos musicales'));
        DB::table('rubros')->insert(array('id' => '299','nombre' => 'Electricidad del automovil'));
        DB::table('rubros')->insert(array('id' => '300','nombre' => 'Lubricentros'));
        DB::table('rubros')->insert(array('id' => '301','nombre' => 'Radiadores y calefaccion automotor'));
        DB::table('rubros')->insert(array('id' => '302','nombre' => 'Embrague automotor'));
        DB::table('rubros')->insert(array('id' => '303','nombre' => 'Autopartes'));
        DB::table('rubros')->insert(array('id' => '304','nombre' => 'Rectificacion de motores'));
        DB::table('rubros')->insert(array('id' => '305','nombre' => 'Frenos automotor'));
        DB::table('rubros')->insert(array('id' => '306','nombre' => 'Rulemanes'));
        DB::table('rubros')->insert(array('id' => '307','nombre' => 'Repuestos y accesorios automotor'));
        DB::table('rubros')->insert(array('id' => '308','nombre' => 'Repuestos diesel'));
        DB::table('rubros')->insert(array('id' => '309','nombre' => 'Repuestos Nafteros'));
        DB::table('rubros')->insert(array('id' => '310','nombre' => 'Talleres mecanicos'));
        DB::table('rubros')->insert(array('id' => '311','nombre' => 'Cristales automotor'));
        DB::table('rubros')->insert(array('id' => '312','nombre' => 'Tapas de cilindro'));
        DB::table('rubros')->insert(array('id' => '313','nombre' => 'Tapiceria automotor'));
        DB::table('rubros')->insert(array('id' => '314','nombre' => 'Tren delantero y suspension '));
        DB::table('rubros')->insert(array('id' => '315','nombre' => 'Elasticos automotor'));
        DB::table('rubros')->insert(array('id' => '316','nombre' => 'Mecanica y electricidad del automotor'));
        DB::table('rubros')->insert(array('id' => '317','nombre' => 'Servicio de gruas'));
        DB::table('rubros')->insert(array('id' => '318','nombre' => 'Mecanica general automotor'));
        DB::table('rubros')->insert(array('id' => '319','nombre' => 'Alineacion y balanceo'));
        DB::table('rubros')->insert(array('id' => '320','nombre' => 'Repuestos motos'));
        DB::table('rubros')->insert(array('id' => '321','nombre' => 'Bombas agua automotor'));
        DB::table('rubros')->insert(array('id' => '322','nombre' => 'Bombas nafta automotor'));
        DB::table('rubros')->insert(array('id' => '323','nombre' => 'Instituto de belleza'));
        DB::table('rubros')->insert(array('id' => '324','nombre' => 'Salon de belleza'));
        DB::table('rubros')->insert(array('id' => '325','nombre' => 'Masajes - sauna'));
        DB::table('rubros')->insert(array('id' => '326','nombre' => 'Cosmetología'));
        DB::table('rubros')->insert(array('id' => '327','nombre' => 'Depilacion'));
        DB::table('rubros')->insert(array('id' => '328','nombre' => 'Peluqueria damas'));
        DB::table('rubros')->insert(array('id' => '329','nombre' => 'Peluqueria hombres'));
        DB::table('rubros')->insert(array('id' => '330','nombre' => 'Peluqueria unisex '));
        DB::table('rubros')->insert(array('id' => '331','nombre' => 'Articulos para peluquerias'));
        DB::table('rubros')->insert(array('id' => '333','nombre' => 'Peluqueria para ninos'));
        DB::table('rubros')->insert(array('id' => '334','nombre' => 'Carpintería de aluminio '));
        DB::table('rubros')->insert(array('id' => '335','nombre' => 'Taller metalurgico '));
        DB::table('rubros')->insert(array('id' => '336','nombre' => 'Carpinteria madera'));
        DB::table('rubros')->insert(array('id' => '337','nombre' => 'Chapas- canos - hierros- metales'));
        DB::table('rubros')->insert(array('id' => '338','nombre' => 'Ceramica'));
        DB::table('rubros')->insert(array('id' => '339','nombre' => 'Herreria de obras'));
        DB::table('rubros')->insert(array('id' => '340','nombre' => 'Aberturas para obras'));
        DB::table('rubros')->insert(array('id' => '341','nombre' => 'Puertas blindadas '));
        DB::table('rubros')->insert(array('id' => '342','nombre' => 'Puertas y ventanas'));
        DB::table('rubros')->insert(array('id' => '343','nombre' => 'Ferretería'));
        DB::table('rubros')->insert(array('id' => '344','nombre' => 'Hormigon premoldeado'));
        DB::table('rubros')->insert(array('id' => '345','nombre' => 'Tratamiento de agua'));
        DB::table('rubros')->insert(array('id' => '346','nombre' => 'Dibujo tecnico'));
        DB::table('rubros')->insert(array('id' => '347','nombre' => 'Estudio arquitectura'));
        DB::table('rubros')->insert(array('id' => '348','nombre' => 'Molduras'));
        DB::table('rubros')->insert(array('id' => '349','nombre' => 'Materiales de construccion '));
        DB::table('rubros')->insert(array('id' => '350','nombre' => 'Sanitarios'));
        DB::table('rubros')->insert(array('id' => '351','nombre' => 'Materiales electricos'));
        DB::table('rubros')->insert(array('id' => '352','nombre' => 'Materiales de gas'));
        DB::table('rubros')->insert(array('id' => '353','nombre' => 'Instalaciones de gas'));
        DB::table('rubros')->insert(array('id' => '354','nombre' => 'Instalaciones de agua'));
        DB::table('rubros')->insert(array('id' => '355','nombre' => 'Instalaciones de luz'));
        DB::table('rubros')->insert(array('id' => '356','nombre' => 'Fabricas de mosaicos'));
        DB::table('rubros')->insert(array('id' => '357','nombre' => 'Revestimientos'));
        DB::table('rubros')->insert(array('id' => '358','nombre' => 'Herrajes'));
        DB::table('rubros')->insert(array('id' => '359','nombre' => 'Empresa de pintura'));
        DB::table('rubros')->insert(array('id' => '360','nombre' => 'Agrimensor'));
        DB::table('rubros')->insert(array('id' => '361','nombre' => 'Articulos deportivos'));
        DB::table('rubros')->insert(array('id' => '362','nombre' => 'Raquetas'));
        DB::table('rubros')->insert(array('id' => '363','nombre' => 'Caza, Pesca, Camping, Nautica'));
        DB::table('rubros')->insert(array('id' => '364','nombre' => 'Armeria-cuchilleria'));
        DB::table('rubros')->insert(array('id' => '365','nombre' => 'Articulos de playa'));
        DB::table('rubros')->insert(array('id' => '366','nombre' => 'Maquinas cortar cesped'));
        DB::table('rubros')->insert(array('id' => '367','nombre' => 'Alfombras y cortinas'));
        DB::table('rubros')->insert(array('id' => '368','nombre' => 'Bordeadoras de cesped'));
        DB::table('rubros')->insert(array('id' => '369','nombre' => 'Articulos electricos y de iluminacion'));
        DB::table('rubros')->insert(array('id' => '370','nombre' => 'Articulos para el hogar'));
        DB::table('rubros')->insert(array('id' => '371','nombre' => 'Freezer'));
        DB::table('rubros')->insert(array('id' => '372','nombre' => 'Antiguedades'));
        DB::table('rubros')->insert(array('id' => '373','nombre' => 'Articulos para jardines y afines'));
        DB::table('rubros')->insert(array('id' => '374','nombre' => 'Bazar '));
        DB::table('rubros')->insert(array('id' => '375','nombre' => 'Articulos de limpieza'));
        DB::table('rubros')->insert(array('id' => '376','nombre' => 'Blanco y manteleria'));
        DB::table('rubros')->insert(array('id' => '377','nombre' => 'Calefaccion y Aire acondicionado'));
        DB::table('rubros')->insert(array('id' => '378','nombre' => 'Cristaleria'));
        DB::table('rubros')->insert(array('id' => '379','nombre' => 'Casa de arte - cuadros'));
        DB::table('rubros')->insert(array('id' => '380','nombre' => 'Artesanías de caña y mimbre'));
        DB::table('rubros')->insert(array('id' => '381','nombre' => 'Muebles y amoblamientos'));
        DB::table('rubros')->insert(array('id' => '382','nombre' => 'Vuelos y paseos en Helicoptero'));
        DB::table('rubros')->insert(array('id' => '383','nombre' => 'Helipuertos'));
        DB::table('rubros')->insert(array('id' => '384','nombre' => 'Muebles para bebes'));
        DB::table('rubros')->insert(array('id' => '385','nombre' => 'Plasticos'));
        DB::table('rubros')->insert(array('id' => '386','nombre' => 'Papeles pintados'));
        DB::table('rubros')->insert(array('id' => '387','nombre' => 'Articulos tapiceria'));
        DB::table('rubros')->insert(array('id' => '388','nombre' => 'Compostura calzados '));
        DB::table('rubros')->insert(array('id' => '389','nombre' => 'Instalacion de gas y sanitarios'));
        DB::table('rubros')->insert(array('id' => '390','nombre' => 'Ventiladores de techo'));
        DB::table('rubros')->insert(array('id' => '391','nombre' => 'Ventiladores de mesa'));
        DB::table('rubros')->insert(array('id' => '392','nombre' => 'Ventiladores de pie'));
        DB::table('rubros')->insert(array('id' => '393','nombre' => 'Balanzas'));
        DB::table('rubros')->insert(array('id' => '394','nombre' => 'Lavaderos automaticos autos'));
        DB::table('rubros')->insert(array('id' => '395','nombre' => 'Lavaderos ropa'));
        DB::table('rubros')->insert(array('id' => '396','nombre' => 'Lavaderos alfombras'));
        DB::table('rubros')->insert(array('id' => '397','nombre' => 'Maquinas de coser'));
        DB::table('rubros')->insert(array('id' => '398','nombre' => 'Maquinas de tejer'));
        DB::table('rubros')->insert(array('id' => '399','nombre' => 'Maquinas de escribir'));
        DB::table('rubros')->insert(array('id' => '400','nombre' => 'Repuestos articulos del hogar'));
        DB::table('rubros')->insert(array('id' => '401','nombre' => 'Tintoreria'));
        DB::table('rubros')->insert(array('id' => '402','nombre' => 'Tecnicos TV.'));
        DB::table('rubros')->insert(array('id' => '403','nombre' => 'Electronica reparaciones'));
        DB::table('rubros')->insert(array('id' => '404','nombre' => 'Afeitadoras '));
        DB::table('rubros')->insert(array('id' => '405','nombre' => 'Afeitadoras reparaciones'));
        DB::table('rubros')->insert(array('id' => '407','nombre' => 'Television- audio'));
        DB::table('rubros')->insert(array('id' => '408','nombre' => 'Videograbadoras'));
        DB::table('rubros')->insert(array('id' => '409','nombre' => 'Radios'));
        DB::table('rubros')->insert(array('id' => '410','nombre' => 'Grabadoras'));
        DB::table('rubros')->insert(array('id' => '411','nombre' => 'Camaras de fotos'));
        DB::table('rubros')->insert(array('id' => '412','nombre' => 'Filmadoras'));
        DB::table('rubros')->insert(array('id' => '413','nombre' => 'Alquiler TV'));
        DB::table('rubros')->insert(array('id' => '414','nombre' => 'Amplificadores musica'));
        DB::table('rubros')->insert(array('id' => '415','nombre' => 'Casas de fotografia'));
        DB::table('rubros')->insert(array('id' => '416','nombre' => 'Estudios fotograficos'));
        DB::table('rubros')->insert(array('id' => '417','nombre' => 'Libreria y papeleria comercial'));
        DB::table('rubros')->insert(array('id' => '418','nombre' => 'Libros'));
        DB::table('rubros')->insert(array('id' => '419','nombre' => 'Editorial'));
        DB::table('rubros')->insert(array('id' => '420','nombre' => 'Fotocopias y duplicacion'));
        DB::table('rubros')->insert(array('id' => '421','nombre' => 'Sellos de goma'));
        DB::table('rubros')->insert(array('id' => '422','nombre' => 'Tarjetas'));
        DB::table('rubros')->insert(array('id' => '423','nombre' => 'Librerias especializadas '));
        DB::table('rubros')->insert(array('id' => '424','nombre' => 'Articulos dibujo y pintura'));
        DB::table('rubros')->insert(array('id' => '425','nombre' => 'Encuadernaciones'));
        DB::table('rubros')->insert(array('id' => '426','nombre' => 'Fantacias'));
        DB::table('rubros')->insert(array('id' => '427','nombre' => 'Souvenir'));
        DB::table('rubros')->insert(array('id' => '428','nombre' => 'Feria artesanal '));
        DB::table('rubros')->insert(array('id' => '429','nombre' => 'Estacionamiento'));
        DB::table('rubros')->insert(array('id' => '430','nombre' => 'Garage'));
        DB::table('rubros')->insert(array('id' => '431','nombre' => 'Parque de diversiones'));
        DB::table('rubros')->insert(array('id' => '432','nombre' => 'Santeria '));
        DB::table('rubros')->insert(array('id' => '433','nombre' => 'Articulos importados'));
        DB::table('rubros')->insert(array('id' => '434','nombre' => 'Radiologia '));
        DB::table('rubros')->insert(array('id' => '435','nombre' => 'Consultorio medico'));
        DB::table('rubros')->insert(array('id' => '436','nombre' => 'Consultorio Psicologo'));
        DB::table('rubros')->insert(array('id' => '437','nombre' => 'Articulos para cirugia '));
        DB::table('rubros')->insert(array('id' => '438','nombre' => 'Electromedicina'));
        DB::table('rubros')->insert(array('id' => '439','nombre' => 'Laboratorio de analisis clinicos'));
        DB::table('rubros')->insert(array('id' => '440','nombre' => 'Lentes de contacto'));
        DB::table('rubros')->insert(array('id' => '441','nombre' => 'Clinica'));
        DB::table('rubros')->insert(array('id' => '442','nombre' => 'Materiales odontologicos'));
        DB::table('rubros')->insert(array('id' => '443','nombre' => 'Equipos de rehabilitacion'));
        DB::table('rubros')->insert(array('id' => '444','nombre' => 'Instrumental medico'));
        DB::table('rubros')->insert(array('id' => '445','nombre' => 'Equipo nebulizacion'));
        DB::table('rubros')->insert(array('id' => '446','nombre' => 'Pedicuria'));
        DB::table('rubros')->insert(array('id' => '447','nombre' => 'Enfermera o Enfermero'));
        DB::table('rubros')->insert(array('id' => '448','nombre' => 'Emergencias medicas'));
        DB::table('rubros')->insert(array('id' => '449','nombre' => 'Marisqueria'));
        DB::table('rubros')->insert(array('id' => '450','nombre' => 'Cafeteria '));
        DB::table('rubros')->insert(array('id' => '451','nombre' => 'Confiterias bailables'));
        DB::table('rubros')->insert(array('id' => '452','nombre' => 'Whiskerias '));
        DB::table('rubros')->insert(array('id' => '453','nombre' => 'Sandwicherias'));
        DB::table('rubros')->insert(array('id' => '454','nombre' => 'Bombonerias'));
        DB::table('rubros')->insert(array('id' => '455','nombre' => 'Casa de te'));
        DB::table('rubros')->insert(array('id' => '456','nombre' => 'cerveceria'));
        DB::table('rubros')->insert(array('id' => '457','nombre' => 'Bowling'));
        DB::table('rubros')->insert(array('id' => '458','nombre' => 'Pool'));
        DB::table('rubros')->insert(array('id' => '459','nombre' => 'Dibujo publicitario'));
        DB::table('rubros')->insert(array('id' => '460','nombre' => 'Agencia de publicidad'));
        DB::table('rubros')->insert(array('id' => '461','nombre' => 'Viajes y turismo'));
        DB::table('rubros')->insert(array('id' => '462','nombre' => 'Computacion'));
        DB::table('rubros')->insert(array('id' => '463','nombre' => 'Computadoras'));
        DB::table('rubros')->insert(array('id' => '464','nombre' => 'Programacion'));
        DB::table('rubros')->insert(array('id' => '465','nombre' => 'Centro de computos'));
        DB::table('rubros')->insert(array('id' => '466','nombre' => 'Instituto de educacion fisica'));
        DB::table('rubros')->insert(array('id' => '467','nombre' => 'Jardin de infantes'));
        DB::table('rubros')->insert(array('id' => '468','nombre' => 'Letreros'));
        DB::table('rubros')->insert(array('id' => '469','nombre' => 'Seguros'));
        DB::table('rubros')->insert(array('id' => '470','nombre' => 'Transporte de cargas'));
        DB::table('rubros')->insert(array('id' => '471','nombre' => 'Transporte de personas'));
        DB::table('rubros')->insert(array('id' => '472','nombre' => 'Taxis'));
        DB::table('rubros')->insert(array('id' => '473','nombre' => 'Remises'));
        DB::table('rubros')->insert(array('id' => '474','nombre' => 'Estudio contable'));
        DB::table('rubros')->insert(array('id' => '475','nombre' => 'Plantas'));
        DB::table('rubros')->insert(array('id' => '476','nombre' => 'Viveros y cultivos'));
        DB::table('rubros')->insert(array('id' => '477','nombre' => 'Compra y venta'));
        DB::table('rubros')->insert(array('id' => '478','nombre' => 'Tabaqueria y cigarrillos'));
        DB::table('rubros')->insert(array('id' => '479','nombre' => 'Taller de afilacion'));
        DB::table('rubros')->insert(array('id' => '480','nombre' => 'Mantenimiento industrial'));
        DB::table('rubros')->insert(array('id' => '481','nombre' => 'Reparacion heladeras y frio'));
        DB::table('rubros')->insert(array('id' => '482','nombre' => 'Electricista'));
        DB::table('rubros')->insert(array('id' => '483','nombre' => 'Articulos publicitarios'));
        DB::table('rubros')->insert(array('id' => '484','nombre' => 'Ambulancias'));
        DB::table('rubros')->insert(array('id' => '485','nombre' => 'Alquiler de autos sin chofer'));
        DB::table('rubros')->insert(array('id' => '486','nombre' => 'Profesores de musica '));
        DB::table('rubros')->insert(array('id' => '487','nombre' => 'Profesores de baile'));
        DB::table('rubros')->insert(array('id' => '488','nombre' => 'Criadero canino'));
        DB::table('rubros')->insert(array('id' => '489','nombre' => 'Colegios privados'));
        DB::table('rubros')->insert(array('id' => '490','nombre' => 'gas envasado'));
        DB::table('rubros')->insert(array('id' => '491','nombre' => 'Maquinas y herramientas'));
        DB::table('rubros')->insert(array('id' => '492','nombre' => 'Muebles y maquinas para oficina'));
        DB::table('rubros')->insert(array('id' => '493','nombre' => 'Ferreteria industrial'));
        DB::table('rubros')->insert(array('id' => '494','nombre' => 'Pasajes micro'));
        DB::table('rubros')->insert(array('id' => '495','nombre' => 'Restauracion de muebles'));
        DB::table('rubros')->insert(array('id' => '496','nombre' => 'Ropa de trabajo'));
        DB::table('rubros')->insert(array('id' => '497','nombre' => 'marcos y cuadros'));
        DB::table('rubros')->insert(array('id' => '498','nombre' => 'Repuestos TV'));
        DB::table('rubros')->insert(array('id' => '499','nombre' => 'Repuestos electrodomesticos'));
        DB::table('rubros')->insert(array('id' => '500','nombre' => 'Venta automotores'));
        DB::table('rubros')->insert(array('id' => '501','nombre' => 'Disfraces'));
        DB::table('rubros')->insert(array('id' => '502','nombre' => 'Reparacion maquinas coser y tejer'));
        DB::table('rubros')->insert(array('id' => '503','nombre' => 'Armas de fuego'));
        DB::table('rubros')->insert(array('id' => '505','nombre' => 'Alarmas'));
        DB::table('rubros')->insert(array('id' => '506','nombre' => 'Servicio seguridad'));
        DB::table('rubros')->insert(array('id' => '507','nombre' => 'Techista'));
        DB::table('rubros')->insert(array('id' => '508','nombre' => 'Planos'));
        DB::table('rubros')->insert(array('id' => '509','nombre' => 'Alimentos para animales'));
        DB::table('rubros')->insert(array('id' => '510','nombre' => 'Herrero'));
        DB::table('rubros')->insert(array('id' => '511','nombre' => 'Editorial libros'));
        DB::table('rubros')->insert(array('id' => '512','nombre' => 'Parabrisas y vidrios para autos'));
        DB::table('rubros')->insert(array('id' => '513','nombre' => 'Alquiler de carpas y sombrillas'));
        DB::table('rubros')->insert(array('id' => '514','nombre' => 'Articulos para celulares'));
        DB::table('rubros')->insert(array('id' => '515','nombre' => 'Almacen de bebidas'));
        DB::table('rubros')->insert(array('id' => '516','nombre' => 'Motel Hotel alojamiento'));
        DB::table('rubros')->insert(array('id' => '517','nombre' => 'Cumpleanos infantiles'));
        DB::table('rubros')->insert(array('id' => '518','nombre' => 'Pancheria'));
        DB::table('rubros')->insert(array('id' => '519','nombre' => 'Hamburgueceria'));
        DB::table('rubros')->insert(array('id' => '520','nombre' => 'Natatorios'));
        DB::table('rubros')->insert(array('id' => '521','nombre' => 'Venta de pasajes '));
        DB::table('rubros')->insert(array('id' => '522','nombre' => 'Pasteleria'));
        DB::table('rubros')->insert(array('id' => '523','nombre' => 'Kartodromo Alquiler de Karting'));
        DB::table('rubros')->insert(array('id' => '524','nombre' => 'Pelotero Inflables'));
        DB::table('rubros')->insert(array('id' => '525','nombre' => 'Estacion de servicio Gas'));
        DB::table('rubros')->insert(array('id' => '526','nombre' => 'Ortopedia Alquiler insumos'));
        DB::table('rubros')->insert(array('id' => '527','nombre' => 'Museos'));
        DB::table('rubros')->insert(array('id' => '528','nombre' => 'Chocolateria'));
        DB::table('rubros')->insert(array('id' => '529','nombre' => 'Aerosillas'));
        DB::table('rubros')->insert(array('id' => '530','nombre' => 'Telefericos Funiculares'));
        DB::table('rubros')->insert(array('id' => '531','nombre' => 'Venta de motos'));
        DB::table('rubros')->insert(array('id' => '532','nombre' => 'Academia de Artes Marciales'));
        DB::table('rubros')->insert(array('id' => '533','nombre' => 'Alquiler de caballos'));
        DB::table('rubros')->insert(array('id' => '534','nombre' => 'Canchas de Padel'));
        DB::table('rubros')->insert(array('id' => '535','nombre' => 'Parque Acuatico'));
        DB::table('rubros')->insert(array('id' => '536','nombre' => 'Reparacion de paragolpes automovil'));
        DB::table('rubros')->insert(array('id' => '537','nombre' => 'Fletes'));
        DB::table('rubros')->insert(array('id' => '538','nombre' => 'Fast Food'));
        DB::table('rubros')->insert(array('id' => '539','nombre' => 'Estudios Juridicos'));
        DB::table('rubros')->insert(array('id' => '540','nombre' => 'Escribanias'));
        DB::table('rubros')->insert(array('id' => '541','nombre' => 'Gestorias'));
        DB::table('rubros')->insert(array('id' => '542','nombre' => 'Estudios contables'));
        DB::table('rubros')->insert(array('id' => '543','nombre' => 'Controles remotos reparacion y venta'));
        DB::table('rubros')->insert(array('id' => '544','nombre' => 'Libreria venta de libros '));
        DB::table('rubros')->insert(array('id' => '545','nombre' => 'Anteojos y lentes de contacto'));
        DB::table('rubros')->insert(array('id' => '546','nombre' => 'Equipamiento medico'));
        DB::table('rubros')->insert(array('id' => '547','nombre' => 'Servicios educativos'));
        DB::table('rubros')->insert(array('id' => '548','nombre' => 'Servicio de cuidado personal'));
        DB::table('rubros')->insert(array('id' => '549','nombre' => 'Baterias Autos'));
        DB::table('rubros')->insert(array('id' => '550','nombre' => 'Baterias para Motos'));
        DB::table('rubros')->insert(array('id' => '551','nombre' => 'Taller frenos Automotor'));
        DB::table('rubros')->insert(array('id' => '552','nombre' => 'Taller Direccion Hidraulica '));
        DB::table('rubros')->insert(array('id' => '553','nombre' => 'Alarmas Monitoreadas ')
      );

    }
}
